[2024-11-03 08:05:22 +0000] [41030] [INFO] Starting gunicorn 23.0.0
[2024-11-03 08:05:22 +0000] [41030] [INFO] Listening at: http://0.0.0.0:8000 (41030)
[2024-11-03 08:05:22 +0000] [41030] [INFO] Using worker: sync
[2024-11-03 08:05:22 +0000] [41032] [INFO] Booting worker with pid: 41032
[2024-11-03 08:06:43 +0000] [41030] [CRITICAL] WORKER TIMEOUT (pid:41032)
[2024-11-03 08:06:43 +0000] [41032] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/ubuntu/qbit/venv/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/home/ubuntu/qbit/venv/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/qbit/venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/ubuntu/qbit/venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/qbit/venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/ubuntu/qbit/venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/home/ubuntu/qbit/venv/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/home/ubuntu/qbit/venv/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/qbit/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2024-11-03 08:06:43 +0000] [41032] [INFO] Worker exiting (pid: 41032)
[2024-11-03 08:06:43 +0000] [41189] [INFO] Booting worker with pid: 41189
[2024-11-03 08:07:14 +0000] [41030] [CRITICAL] WORKER TIMEOUT (pid:41189)
[2024-11-03 08:07:14 +0000] [41189] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/ubuntu/qbit/venv/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/home/ubuntu/qbit/venv/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/qbit/venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/ubuntu/qbit/venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/qbit/venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/ubuntu/qbit/venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/home/ubuntu/qbit/venv/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/home/ubuntu/qbit/venv/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/qbit/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2024-11-03 08:07:14 +0000] [41189] [INFO] Worker exiting (pid: 41189)
[2024-11-03 08:07:14 +0000] [41190] [INFO] Booting worker with pid: 41190
[2024-11-03 08:12:23 +0000] [41030] [INFO] Handling signal: term
[2024-11-03 08:12:23 +0000] [41190] [INFO] Worker exiting (pid: 41190)
[2024-11-03 08:12:24 +0000] [41030] [INFO] Shutting down: Master
[2024-11-03 08:13:41 +0000] [42302] [INFO] Starting gunicorn 23.0.0
[2024-11-03 08:13:41 +0000] [42302] [INFO] Listening at: http://0.0.0.0:8000 (42302)
[2024-11-03 08:13:41 +0000] [42302] [INFO] Using worker: sync
[2024-11-03 08:13:41 +0000] [42304] [INFO] Booting worker with pid: 42304
Not Found: /static/Qbit/css/styles.css
[2024-11-03 08:14:28 +0000] [42302] [CRITICAL] WORKER TIMEOUT (pid:42304)
[2024-11-03 08:14:28 +0000] [42304] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/ubuntu/qbit/venv/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 133, in handle
    req = next(parser)
          ^^^^^^^^^^^^
  File "/home/ubuntu/qbit/venv/lib/python3.12/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/qbit/venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 259, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/ubuntu/qbit/venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/qbit/venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 271, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/ubuntu/qbit/venv/lib/python3.12/site-packages/gunicorn/http/message.py", line 262, in get_data
    data = unreader.read()
           ^^^^^^^^^^^^^^^
  File "/home/ubuntu/qbit/venv/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 36, in read
    d = self.chunk()
        ^^^^^^^^^^^^
  File "/home/ubuntu/qbit/venv/lib/python3.12/site-packages/gunicorn/http/unreader.py", line 63, in chunk
    return self.sock.recv(self.mxchunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/qbit/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
SystemExit: 1
[2024-11-03 08:14:28 +0000] [42304] [INFO] Worker exiting (pid: 42304)
[2024-11-03 08:14:29 +0000] [42377] [INFO] Booting worker with pid: 42377
Not Found: /static/Qbit/css/styles.css
Not Found: /static/Qbit/css/styles.css
Not Found: /static/Qbit/css/styles.css
[2024-11-03 08:16:44 +0000] [42302] [INFO] Handling signal: term
[2024-11-03 08:16:44 +0000] [42377] [INFO] Worker exiting (pid: 42377)
[2024-11-03 08:16:44 +0000] [42302] [INFO] Shutting down: Master
